In [8]:
import numpy as np
from descompLU import *

In [9]:
A = np.array([[0,1,2],[1,1,0],[1,0,3]])
P = np.array([[0,1,0],[1,0,0],[0,0,1]])
PA = P@A
LU = LU(PA)

print(PA, "\n")

print(LU[0],"\n")
print(LU[1])

[[1 1 0]
 [0 1 2]
 [1 0 3]] 

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 1. -1.  1.]] 

[[1 1 0]
 [0 1 2]
 [0 0 5]]


In [11]:
a = np.array([[0.001,2],[1,1]])
b = np.array([8,2])

np.linalg.solve(a,b)

array([-2.0010005,  4.0010005])