In [9]:
import numpy as np

In [10]:
# FUNCIONES PARA RESOLVER SISTEMAS TENIENDO L Y U

def resultadoEnPosicion(U, b, x, pos):
    res = b[pos]
    largo = len(b)
    for i in range(largo):
        if(i != pos):
            res = res - U[pos][i] * x[i]
    return (res / U[pos][pos])


def Uxb(U, b): #solo sirve si U es triangular superior
    largo = len(b)
    res = np.zeros(largo)
    for i in range(largo):
        pos = largo - 1 - i #posicion en la diagonal
        res[pos] = resultadoEnPosicion(U,b,res,pos)
    return res


def Lyx(L, x): #solo sirve si U es triangular inferior
    largo = len(x)
    res = np.zeros(largo)
    for i in range(largo):
        res[i] = resultadoEnPosicion(L,x,res,i)
    return res
    





In [14]:
#FUNCIONES PARA SACAR LA DESCOMPO LU

def matarBajoPivote(U, F, L):
    pivote = U[F][F]
    for i in range(len(U) - F - 1):
        cociente = U[F + i + 1][F] / pivote 
        U[F + i + 1] = U[F + i + 1] - U[F] * cociente
        L[F + i + 1][F] = cociente
    return (U, L)

def LU(A):
    U = np.copy(A)
    L = np.eye(len(U))
    for i in range(len(U)-1):
        
        matrices = matarBajoPivote(U, i + 1, L)
        U = matrices[0]
        L = matrices[1]
    return (L, U)

    


In [15]:

A = np.array([[1,-1,0,1],[0,1,4,0],[2,-1,0,-2],[-3,3,0,-1]])
b = np.array([1,-7,-5,1])


print(A, "\n")

L = LU(A)[0]
U = LU(A)[1]

print(A, "\n")

print(L@U, "\n")

print(LU(A)[0], "\n")

print(LU(A)[1], "\n")


[[ 1 -1  0  1]
 [ 0  1  4  0]
 [ 2 -1  0 -2]
 [-3  3  0 -1]] 

[[ 1 -1  0  1]
 [ 0  1  4  0]
 [ 2 -1  0 -2]
 [-3  3  0 -1]] 

[[ 1. -1.  0.  1.]
 [ 0.  1.  4.  0.]
 [ 2. -1.  0. -2.]
 [-3.  3.  0. -1.]] 

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0. -1.  1.  0.]
 [ 0.  3. -3.  1.]] 

[[ 1 -1  0  1]
 [ 0  1  4  0]
 [ 2  0  4 -2]
 [ 3  0  0 -7]] 



In [16]:
A = np.array([[0,1,2],[1,1,0],[1,0,3]])
P = np.array([[0,1,0],[1,0,0],[0,0,1]])
PA = P@A
LU = LU(PA)

print(PA, "\n")

print(LU[0],"\n")
print(LU[1])

[[1 1 0]
 [0 1 2]
 [1 0 3]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1 1 0]
 [0 1 2]
 [1 0 3]]


In [13]:
A = np.array([[1,-1,0,1],[0,1,4,0],[2,-1,0,-2],[-3,3,0,-1]])
b = np.array([1,-7,-5,1])

def resolverLU(A, b):
    t = LU(A)
    y = Lyx(t[0], b)
    return Uxb(t[1], y)

print(resolverLU(A, b))

print(np.linalg.solve(A,b))

[ 0.  1. -2.  2.]
[-8.8817842e-16  1.0000000e+00 -2.0000000e+00  2.0000000e+00]
