In [1]:
import numpy as np


In [122]:

def productoDiagonal(D,b):
    result = b.astype(float)
    for i in range(len(D)):
        result[i] = D[i]*result[i]
    return result


def generarJacobi(A,b):
    D = np.diag(A)
    L = np.tril(A,-1)
    U = np.triu(A,+1)
    D = 1/D
    M = productoDiagonal(-D,(L + U))
    b0 = productoDiagonal(D,b)
    
    return (M,b0)

def resolverJacobi(A,b,tope,tolerancia):
    T = generarJacobi(A,b)
    M = T[0]
    b0 = T[1]
    result = np.random.rand(len(A))
    i = 0
    while True:
        v0 = result
        result = M @ result + b0
        i = i+1
        if (np.linalg.norm((v0-result), np.Inf) < tolerancia):
            print(i)
            break
        elif (i >= tope):
            print(i)
            print("se excedió el numero de iteraciones")
            break
    return result


In [123]:
A = np.array([[3,1,1],[2,6,1],[1,1,4]])
b = np.array([5,9,6])

print(np.linalg.solve(A,b))
print(resolverJacobi(A,b,400,0.0000001))

[1. 1. 1.]
28
[0.99999997 0.99999998 0.99999998]


In [124]:
A = np.array([[3.,1.,1.],[2.,6.,1.],[1.,1.,4.]])
b = np.array([5.,9.,6.])

print(np.linalg.solve(A,b))
print(generarJacobi(A,b))
resolverJacobi(A,b,20,0.1)




[1. 1. 1.]
(array([[-0.        , -0.33333333, -0.33333333],
       [-0.33333333, -0.        , -0.16666667],
       [-0.25      , -0.25      , -0.        ]]), array([1.66666667, 1.5       , 1.5       ]))
5


array([1.02923109, 1.02431874, 1.02386109])