In [2]:
import numpy as np


In [3]:
P = np.array([[0.25,0.5,0.5,0.5],[0.25,0.5,0,0],[0.25,0,0.5,0],[0.25,0,0,0.5]])
avals = np.linalg.eigvals(P)
print(avals)

[-0.25  1.    0.5   0.5 ]


In [4]:
v0 = np.array([1,0,0,0])
for i in range(4):
    v0 = P @ v0
print(np.round(v0,2))

[0.4 0.2 0.2 0.2]


In [82]:
def potenciarMatriz(P,n):
    PI = P
    for i in range(n):
        PI = P @ PI
    return PI
print(np.round(PI,2))
print(range(1,5)[3])

[[0.4 0.4 0.4 0.4]
 [0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2]]
4


In [54]:
distancia = 20 
probabilidad = 0.8

def crearMatriz(n, p):
    P = np.zeros(shape=(n, n))
    P[0][0] = 1
    P[n-1][n-1] = 1
    for i in range(1,n-1):
        P[i-1][i] = 1-p
        P[i+1][i] = p
    return P
P = crearMatriz(distancia,probabilidad)
#ultima columna = casa

    

In [40]:
v0 = np.zeros(shape=(1,distancia))
v0 = v0[0]
v0[10]=1
print(v0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [41]:
epsilon = 0.000001
def ruinaApostador(P, v0, epsilon):
    while(True):
        transformado = P @ v0
        if (np.linalg.norm((transformado - v0),1) <= epsilon):
            v0 = transformado
            break
        else:
            v0 = transformado
    return v0
        
print(np.round(ruinaApostador(P, v0, epsilon), 5))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [42]:
v1 = np.zeros(shape=(1,distancia))
v1 = v1[0]
v1[1]=1
print(np.round(ruinaApostador(P, v1, epsilon), 5))

[0.25 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.75]


In [56]:
print(np.round(potenciarMatriz(P),3))

[[1.    0.25  0.062 0.016 0.004 0.001 0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.001 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.001 0.    0.001 0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.003 0.    0.002 0.    0.001 0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.006 0.    0.003 0.    0.001 0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.012 0.    0.008 0.    0.003 0.    0.001 0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.021 0.    0.01  0.    0.003 0.    0.001 0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.035 0.    0.02

In [86]:
P = np.array([[0.5,0.5,0,0],[0.5,0,0,0],[0,0.5,0,1],[0,0,1,0]])
eig = np.linalg.eig(P)
evecs = eig[1]
evals = eig[0]
del(eig)


def extraerEvec(evecs, n):
    evec = np.zeros(len(evecs))
    for i in range(len(evecs)):
        evec[i] = evecs[i][n]
    return evec
        
evec = extraerEvec(evecs,3)



def matrizDiagonal(evals):
    diagonal = np.zeros(shape=(len(evals),len(evals)))
    for i in range(len(evals)):
        diagonal[i][i]= evals[i]
    return diagonal

diagonal = matrizDiagonal(evals)

v0 = np.array([0.5,0,0.5,0])
v0b = np.linalg.solve(evecs,v0)


print(np.round(evecs,4),"\n")
print(diagonal,"\n")

print(evecs@(potenciarMatriz(diagonal,100))@v0b)

        


[[ 0.     -0.4717  0.608  -0.    ]
 [ 0.      0.7632  0.3757  0.    ]
 [ 0.7071  0.1304 -0.4399  0.7071]
 [-0.7071 -0.4219 -0.5438  0.7071]] 

[[-1.          0.          0.          0.        ]
 [ 0.         -0.30901699  0.          0.        ]
 [ 0.          0.          0.80901699  0.        ]
 [ 0.          0.          0.          1.        ]] 

[1.82891948e-10 1.13033428e-10 2.00000000e-01 8.00000000e-01]
